name: Feature request
description: A new feature or an improvement
labels: [idea]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does it solve
      description: Describe the situation where you would need it.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: How you imagine it
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
