/** Colori sobri tra cui scegliere per categorie e conti (coerenti con la palette di default). */
export const PICKER_COLORS = [
  '#6E9E7B',
  '#5E9A77',
  '#4F9690',
  '#6EA398',
  '#5E9AA3',
  '#6887AB',
  '#626F96',
  '#7A7DB0',
  '#8B7BAA',
  '#B07189',
  '#BF6B66',
  '#C47F68',
  '#C98B5E',
  '#C4A35E',
  '#9C8878',
  '#8E8E93',
] as const;

/** Icone (MaterialCommunityIcons) proposte per le categorie. */
export const CATEGORY_ICONS = [
  'food-apple',
  'cart',
  'silverware-fork-knife',
  'coffee',
  'glass-cocktail',
  'home',
  'flash',
  'water',
  'wifi',
  'cellphone',
  'bus',
  'car',
  'gas-station',
  'taxi',
  'airplane',
  'train',
  'bike',
  'hospital-box',
  'pill',
  'tshirt-crew',
  'shoe-heel',
  'toothbrush',
  'content-cut',
  'gamepad-variant',
  'movie',
  'music',
  'book-open-variant',
  'school',
  'basketball',
  'dumbbell',
  'paw',
  'baby-carriage',
  'gift',
  'heart',
  'briefcase',
  'tools',
  'cash',
  'piggy-bank',
  'bank',
  'chart-line',
  'credit-card',
  'hand-coin',
  'star',
  'dots-horizontal',
] as const;

/** Icone proposte per i conti. */
export const ACCOUNT_ICONS = [
  'cash',
  'wallet',
  'credit-card',
  'bank',
  'piggy-bank',
  'safe',
  'briefcase',
  'chart-line',
] as const;
